spring:
  datasource:
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    url: ${DB_URL:jdbc:mysql://mysql:3306/room_bookings}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect